//importing soSomeMath from math.js with or without extension...
import doSomeMath from './math.js'

//importing the other modules...
//since these modules were not exported as default we have to destructure...
import { addTwo, multipl, subtracty } from './math.js'

//to import everything remaining...
import * as everything from './math.js'

console.log(addTwo(5,5))
console.log(doSomeMath.addTwo(5,5))
console.log(everything)

//a package is a module or a collection of modules...For instance, react, reactDOM are packages...